GestionareRegimuri/Controllers/BoalaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GestionareRegimuri.Data;
using GestionareRegimuri.Models;
using Microsoft.AspNetCore.Authorization;
using GestionareRegimuri.Utils.Services;
using GestionareRegimuri.ViewModels;
using Microsoft.AspNetCore.Identity;
using GestionareRegimuri.Repository.Interfaces;

namespace GestionareRegimuri.Controllers
{
    public class BoalaController : Controller
    {
        private readonly IBoalaRepository _boalaRepository;

        public BoalaController(IBoalaRepository boalaRepository)
        {
            _boalaRepository = boalaRepository;
        }

        //Get: Boala
        public async Task<IActionResult> Index(string childname)
        {
            if (string.IsNullOrEmpty(childname))
            {
                return View(await _boalaRepository.FindAll().ToListAsync());
            }
            return View(await _boalaRepository.FindByCondition(b => b.Nume.ToUpper().Contains(childname.ToUpper())).ToListAsync());
        }

        // GET: Boala/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Boala/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(BoalaViewModel boalaVM)
        {
            if (ModelState.IsValid)
            {
                Boala boala = new Boala()
                {
                    BoalaID = boalaVM.BoalaID,
                    Nume = boalaVM.Nume
                };
                _boalaRepository.Create(boala);
                _boalaRepository.Save();
                return RedirectToAction(nameof(Edit), new { id = boala.BoalaID });
            }
            return View(_boalaRepository);
        }

        // GET: Boala/Edit/5
        public async Task<IActionResult> Edit(int id)
        {

            var boala = await _boalaRepository.FindByCondition(m => m.BoalaID == id).FirstOrDefaultAsync();
            if (boala == null)
            {
                return NotFound();
            }
            BoalaViewModel boalaVM = new BoalaViewModel()
            {
                BoalaID = boala.BoalaID,
                Nume = boala.Nume
            };

            return View(boalaVM);
        }

        // POST: Boala/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, BoalaViewModel boalaVM)
        {
            if (ModelState.IsValid)
            {

                Boala boala = _boalaRepository.FindByCondition(m => m.BoalaID == id).FirstOrDefault();

                if (boala == null)
                {
                    return NotFound();
                }

                //setting other values
                boala.BoalaID = boalaVM.BoalaID;
                boala.Nume = boalaVM.Nume;

                //success
                _boalaRepository.Update(boala);
                _boalaRepository.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(boalaVM);
        }

        // GET: Boala/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var boala = _boalaRepository.FindByCondition(m => m.BoalaID == id).FirstOrDefault();
            if (boala == null)
            {
                return NotFound();
            }

            _boalaRepository.Delete(boala);
            _boalaRepository.Save();

            return RedirectToAction(nameof(Index));
        }
    }
}

GestionareRegimuri/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GestionareRegimuri.Data;
using GestionareRegimuri.Models;
using Microsoft.AspNetCore.Authorization;
using GestionareRegimuri.Utils.Services;
using GestionareRegimuri.ViewModels;
using Microsoft.AspNetCore.Identity;
using GestionareRegimuri.Repository.Interfaces;

namespace GestionareRegimuri.Controllers
{
    public class ForumController : Controller
    {
        private readonly IForumRepository _forumRepository;
        private readonly UserManager<User> _userManager;

        public ForumController(IForumRepository forumRepository, UserManager<User> userManager)
        {
            _forumRepository = forumRepository;
            _userManager = userManager;
        }

        //Get: Forum
        public async Task<IActionResult> Index()
        {
            return View(await _forumRepository.FindAll()
                .Include(f => f.Mesaje)
                .Include(f => f.User)
                .Select(f => new ForumViewModel() { 
                    DiscutieID = f.DiscutieID,
                    Nume = f.User.UserName,
                    Titlu = f.Titlu,
                    Data = f.Mesaje.OrderBy(m => m.Data).LastOrDefault() == null ? null : f.Mesaje.OrderBy(m => m.Data).LastOrDefault().Data
            }).ToListAsync());
        }

        // GET: Forum/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Forum/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ForumViewModel forumVM)
        {
            if (ModelState.IsValid)
            {
                Forum forum = new Forum()
                {
                    DiscutieID = forumVM.DiscutieID,
                    UserID = int.Parse(_userManager.GetUserId(User)),
                    Titlu = forumVM.Titlu,
                };
                _forumRepository.Create(forum);
                _forumRepository.Save();
                return RedirectToAction(nameof(Details), new { id = forum.DiscutieID });
            }
            return View(forumVM);
        }

        // GET: Forum/Edit/5
        public async Task<IActionResult> Edit(int id)
        {

            var forum = await _forumRepository.FindByCondition(m => m.DiscutieID == id).FirstOrDefaultAsync();
            if (forum == null)
            {
                return NotFound();
            }
            ForumViewModel forumVM = new ForumViewModel()
            {
                DiscutieID = forum.DiscutieID,
                Nume = _userManager.GetUserName(User),
                Titlu = forum.Titlu,
            };

            return View(forumVM);
        }

        // POST: Forum/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ForumViewModel forumVM)
        {
            if (ModelState.IsValid)
            {

                Forum forum = _forumRepository.FindByCondition(m => m.DiscutieID == forumVM.DiscutieID).FirstOrDefault();

                if (forum == null)
                {
                    return NotFound();
                }

                //setting other values
                forum.DiscutieID = forumVM.DiscutieID;
                forum.Titlu = forumVM.Titlu;

                //success
                _forumRepository.Update(forum);
                _forumRepository.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(forumVM);
        }

        public async Task<IActionResult> Details (int id)
        {

            var forum = await _forumRepository.FindByCondition(m => m.DiscutieID == id)
                .Include(f => f.Mesaje).ThenInclude(m => m.User)
                .FirstOrDefaultAsync();
            if (forum == null)
            {
                return NotFound();
            }
            

            return View(forum);
        }

        // GET: Forum/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forum = _forumRepository.FindByCondition(m => m.DiscutieID == id).FirstOrDefault();
            if (forum == null)
            {
                return NotFound();
            }

            _forumRepository.Delete(forum);
            _forumRepository.Save();

            return RedirectToAction(nameof(Index));
        }
    }
}

GestionareRegimuri/Controllers/RetetaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GestionareRegimuri.Data;
using GestionareRegimuri.Models;
using Microsoft.AspNetCore.Authorization;
using GestionareRegimuri.Utils.Services;
using GestionareRegimuri.ViewModels;
using Microsoft.AspNetCore.Identity;
using GestionareRegimuri.Repository.Interfaces;

namespace GestionareRegimuri.Controllers
{
    [Authorize(Roles = "Administrator,Medic")]
    public class RetetaController : Controller
    {
        private readonly IRetetaRepository _retetaRepository;
        private readonly IBoalaService _boalaService;

        public RetetaController(IRetetaRepository retetaRepository, IBoalaService boalaService)
        {
            _retetaRepository = retetaRepository;
            _boalaService = boalaService;
        }

        [AllowAnonymous]
        //Get: Reteta
        public async Task<IActionResult> Index(string childname)
        {
            if (string.IsNullOrEmpty(childname))
            {
                return View(await _retetaRepository.FindAll().ToListAsync());
            }


            return View(await _retetaRepository.FindByCondition(
                r => r.RetetaNume.ToUpper().Contains(childname.ToUpper()) ||
                     r.Boli.Select(b => b.Nume.ToUpper())
                        .Any(b => b.Contains(childname))
                     ).ToListAsync());
        }

        [AllowAnonymous]
        // GET: Aliment/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reteta = await _retetaRepository.FindByCondition(m => m.RetetaID == id)
                .FirstOrDefaultAsync();

            if (reteta == null)
            {
                return NotFound();
            }

            else
            {
                ViewBag.Boli = new int[0];
            }
            return View(reteta);
        }

        // GET: Reteta/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Reteta/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(RetetaViewModel retetaVM)
        {
            if (ModelState.IsValid)
            {
                Reteta reteta = new Reteta()
                {
                    RetetaID = retetaVM.RetetaID,
                    Link = retetaVM.Link,
                    RetetaNume = retetaVM.RetetaNume,
                    Boli = _boalaService.parseBoalas(retetaVM.Boli)
                };
                _retetaRepository.Create(reteta);
                _retetaRepository.Save();
                return RedirectToAction(nameof(Edit), new { id = reteta.RetetaID });
            }
            return View(_retetaRepository);
        }

        // GET: Reteta/Edit/5
        public async Task<IActionResult> Edit(int id)
        {

            var reteta = await _retetaRepository.FindByCondition(m => m.RetetaID == id).Include(r => r.Boli).FirstOrDefaultAsync();
            if (reteta == null)
            {
                return NotFound();
            }
            RetetaViewModel retetaVM = new RetetaViewModel()
            {
                RetetaID = reteta.RetetaID,
                Boli =  _boalaService.stringifyBoalas(reteta.Boli),
                RetetaNume = reteta.RetetaNume,
                Link = reteta.Link
            };

            return View(retetaVM);
        }

        // POST: Reteta/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(RetetaViewModel retetaVM)
        {
            if (ModelState.IsValid)
            {

                Reteta reteta = _retetaRepository.FindByCondition(m => m.RetetaID == retetaVM.RetetaID).FirstOrDefault();

                if (reteta == null)
                {
                    return NotFound();
                }

                _retetaRepository.LoadCollection(reteta, r => r.Boli);

                //setting other values
                reteta.RetetaID = retetaVM.RetetaID;
                reteta.Boli = _boalaService.parseBoalas(retetaVM.Boli);
                reteta.RetetaNume = retetaVM.RetetaNume;
                reteta.Link = retetaVM.Link;

                //success
                _retetaRepository.Update(reteta);
                _retetaRepository.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(retetaVM);
        }

        // GET: Boala/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reteta = _retetaRepository.FindByCondition(m => m.RetetaID == id).FirstOrDefault();
            if (reteta == null)
            {
                return NotFound();
            }

            _retetaRepository.Delete(reteta);
            _retetaRepository.Save();

            return RedirectToAction(nameof(Index));
        }
    }
}

GestionareRegimuri/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GestionareRegimuri</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gestionare Regimuri</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @if (Context.Request.Path.ToString().Equals("/Alimente", StringComparison.OrdinalIgnoreCase))
                            {
                                <a class="nav-link text-black-50">Alimente</a>
                            }
                            else
                            {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Aliment" asp-action="Index">Alimente</a>
                            }
                        </li>
                        <li class="nav-item">
                            @if (Context.Request.Path.ToString().Equals("/Boala", StringComparison.OrdinalIgnoreCase))
                            {
                                <a class="nav-link text-black-50">Boli</a>
                            }
                            else
                            {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Boala" asp-action="Index">Boli</a>
                            }
                        </li>
                        <li class="nav-item">
                            @if (Context.Request.Path.ToString().Equals("/Retete", StringComparison.OrdinalIgnoreCase))
                            {
                                <a class="nav-link text-black-50">Retete</a>
                            }
                            else
                            {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reteta" asp-action="Index">Rețete</a>
                            }
                        </li>
                        <li class="nav-item">
                            @if (Context.Request.Path.ToString().Equals("/Forum", StringComparison.OrdinalIgnoreCase))
                            {
                                <a class="nav-link text-black-50">Forum</a>
                            }
                            else
                            {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Forum" asp-action="Index">Forum</a>
                            }
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Gestionare Regimuri - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>