GestionareRegimuri/Models/Contraindicatii.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GestionareRegimuri.Models
{
    public class Contraindicatii
    {
        [Key]
        public int ContraindicatieID { get; set; }
        [Required]
        public int AlimentID { get; set; }
        [Required]
        public int BoalaID { get; set; }
        [Required]
        public string Motiv { get; set; }

        public Aliment Aliment { get; set; }
        public Boala Boala { get; set; }
    }
}

GestionareRegimuri/ViewModels/ContraindicatiiViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GestionareRegimuri.ViewModels
{
    public class ContraindicatiiViewModel
    {
        public int ContraindicatieID { get; set; }
        [Required]
        public int AlimentID { get; set; }
        [Required]
        public string Boala { get; set; }
        [Required]
        public string Motiv { get; set; }
    }
}

GestionareRegimuri/Controllers/AlimentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GestionareRegimuri.Data;
using GestionareRegimuri.Models;
using GestionareRegimuri.Repository.Interfaces;

namespace GestionareRegimuri.Controllers
{
    public class AlimentController : Controller
    {
        //private readonly ApplicationDbContext _context;
        private readonly IAlimentRepository _alimentRepository;
        private readonly IUserRepository _userRepository;

        public AlimentController(IAlimentRepository alimentRepository, IUserRepository userRepository)
        {
            _alimentRepository = alimentRepository;
            _userRepository = userRepository;
        }

        // GET: Aliment
        public async Task<IActionResult> Index(string childname)
        {
            if (string.IsNullOrEmpty(childname))
            {
                return View(await _alimentRepository.FindAll().ToListAsync());
            }
            return View(await _alimentRepository.FindByCondition(b => b.Nume.ToUpper().Contains(childname.ToUpper())).ToListAsync());
        }
        //{
        //    return View(await alimentRepository.FindAll().ToListAsync());
        //}

        // GET: Aliment/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aliment = await _alimentRepository.FindByCondition(m => m.AlimentID == id)
                .Include(a => a.Indicatii)
                    .ThenInclude(i => i.Boala)
                .Include(a => a.Contraindicatii)
                    .ThenInclude(i => i.Boala)
                .FirstOrDefaultAsync();

            if (aliment == null)
            {
                return NotFound();
            }

            if (User.Identity.IsAuthenticated)
            {
                var user = await _userRepository.getCurrentUserAsync(User);
                _userRepository.LoadCollection(user, u => u.Boli);
                ViewBag.Boli = user.Boli.Select(b => b.BoalaID).ToArray();
            }
            else
            {
                ViewBag.Boli = new int[0];
            }
            return View(aliment);
        }

        // GET: Aliment/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Aliment/Create/1
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("AlimentID,Nume,Categorie,Glucide,Proteine,Lipide,Calorii")] Aliment aliment)
        {
            if (ModelState.IsValid)
            {
                _alimentRepository.Create(aliment);
                _alimentRepository.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(aliment);
        }

        // GET: Aliment/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aliment = await _alimentRepository.FindByCondition(m => m.AlimentID == id).FirstOrDefaultAsync();
            if (aliment == null)
            {
                return NotFound();
            }
            return View(aliment);
        }

        // POST: Aliment/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AlimentID,Nume,Categorie,Glucide,Proteine,Lipide,Calorii")] Aliment aliment)
        {
            if (id != aliment.AlimentID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _alimentRepository.Update(aliment);
                    _alimentRepository.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await _alimentRepository.FindByCondition(m => m.AlimentID == id).AnyAsync())
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(aliment);
        }

        // GET: Aliment/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aliment = _alimentRepository.FindByCondition(m => m.AlimentID == id).FirstOrDefault();
            if (aliment == null)
            {
                return NotFound();
            }

            return View(aliment);
        }

        // POST: Aliment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var aliment = await _alimentRepository.FindByCondition(m => m.AlimentID == id).FirstOrDefaultAsync();
            _alimentRepository.Delete(aliment);
            _alimentRepository.Save();
            return RedirectToAction(nameof(Index));
        }
    }
}

GestionareRegimuri/Views/Contraindicatii/Create.cshtml
@model GestionareRegimuri.ViewModels.ContraindicatiiViewModel

@{ ViewData["Title"] = "Creare Contraindicatii"; }

<h1>Creare</h1>

<h4>Contraindicatie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Contraindicatii" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="AlimentID" type="hidden" />
            <div class="form-group">
                <label asp-for="Boala" class="control-label"></label>
                <input asp-for="Boala" class="form-control" />
                <span asp-validation-for="Boala" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Motiv" class="control-label"></label>
                <input asp-for="Motiv" class="form-control" />
                <span asp-validation-for="Motiv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


<div>
    <a asp-action="Index">Index</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GestionareRegimuri/Views/Contraindicatii/Edit.cshtml
@model GestionareRegimuri.ViewModels.ContraindicatiiViewModel

@{ ViewData["Title"] = "Editare Contraindicatii"; }


<h1>Editare</h1>

<h4>Contraindicatie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ContraindicatieID" />
            <div class="form-group">
                <label asp-for="AlimentID" class="control-label"></label>
                <input asp-for="AlimentID" class="form-control" />
                <span asp-validation-for="AlimentID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Boala" class="control-label"></label>
                <input asp-for="Boala" class="form-control" />
                <span asp-validation-for="Boala" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Motiv" class="control-label"></label>
                <input asp-for="Motiv" class="form-control" />
                <span asp-validation-for="Motiv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvare" class="btn btn-primary" />
                <button asp-action="Delete" class="btn btn-primary" asp-route-id="@Context.Request.Query["id"]">Sterge</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Aliment" asp-action="Details" asp-route-id="@Model.AlimentID">Anulare</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GestionareRegimuri/Views/Contraindicatii/Index.cshtml
@model IEnumerable<GestionareRegimuri.Models.Contraindicatii>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Creare noua contraindicatie</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Motiv)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Aliment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Boala)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Motiv)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Aliment.Categorie)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Boala.Nume)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ContraindicatieID">Editare</a> |
                    <a asp-action="Details" asp-route-id="@item.ContraindicatieID">Detalii</a> |
                    <a asp-action="Delete" asp-route-id="@item.ContraindicatieID">Sterge</a>
                </td>
            </tr>
        }
    </tbody>
</table>