GestionareRegimuri/Models/Indicatii.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GestionareRegimuri.Models
{
    public class Indicatii
    {
        public int IndicatiiID { get; set; }
        [Required]
        public int AlimentID { get; set; }
        [Required]
        public int BoalaID { get; set; }
        [Required]
        public string Motiv { get; set; }

        public Aliment Aliment { get; set; }

        public Boala Boala { get; set; }
    }
}

GestionareRegimuri/ViewModels/IndicatiiViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GestionareRegimuri.ViewModels
{
    public class IndicatiiViewModel
    {
        public int IndicatiiID { get; set; }
        [Required]
        public int AlimentID { get; set; }
        [Required]
        public string Boala { get; set; }
        [Required]
        public string Motiv { get; set; }
    }
}

GestionareRegimuri/Controllers/IndicatiiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GestionareRegimuri.Data;
using GestionareRegimuri.Models;
using Microsoft.AspNetCore.Authorization;
using GestionareRegimuri.Utils.Services;
using GestionareRegimuri.ViewModels;
using Microsoft.AspNetCore.Identity;
using GestionareRegimuri.Repository.Interfaces;


namespace GestionareRegimuri.Controllers
{
    [Authorize(Roles = "Administrator,Medic")]
    public class IndicatiiController : Controller
    {
        private readonly IIndicatiiRepository _indicatiiRepository;
        private readonly IBoalaRepository _boalaRepository;

        public IndicatiiController(IIndicatiiRepository indicatiiRepository, IBoalaRepository boalaRepository)
        {
            _indicatiiRepository = indicatiiRepository;
            _boalaRepository = boalaRepository;
        }

        //Get: Indicatii
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return View(await _indicatiiRepository.FindAll().ToListAsync());
        }

        // GET: Indicatii/Create
        public IActionResult Create(int id)
        {
            IndicatiiViewModel indicatiiVM = new IndicatiiViewModel()
            {
                AlimentID = id
            };
            return View(indicatiiVM);
        }

        // POST: Indicatii/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(IndicatiiViewModel indicatiiVM)
        {
            if (ModelState.IsValid)
            {
                var boala = _boalaRepository.FindByCondition(boala => boala.Nume == indicatiiVM.Boala).FirstOrDefault();
                if (boala == null)
                {
                    boala = new Boala() { Nume = indicatiiVM.Boala };
                    _boalaRepository.Create(boala);
                    _boalaRepository.Save();
                }
                Indicatii indicatii = new Indicatii()
                {
                    AlimentID = indicatiiVM.AlimentID,
                    BoalaID = boala.BoalaID,
                    Motiv = indicatiiVM.Motiv
                };
                _indicatiiRepository.Create(indicatii);
                _indicatiiRepository.Save();
                return RedirectToAction(nameof(Edit), new { id = indicatii.IndicatiiID });
            }
            return View(indicatiiVM);
        }

        // GET: Indicatii/Edit/5
        public async Task<IActionResult> Edit(int id)
        {

            var indicatii = await _indicatiiRepository.FindByCondition(m => m.IndicatiiID == id).Include(c => c.Boala).FirstOrDefaultAsync();
            if (indicatii == null)
            {
                return NotFound();
            }
            IndicatiiViewModel indicatieVM = new IndicatiiViewModel()
            {
                IndicatiiID = indicatii.IndicatiiID,
                AlimentID = indicatii.AlimentID,
                Boala = indicatii.Boala.Nume,
                Motiv = indicatii.Motiv
            };

            return View(indicatieVM);
        }

        // POST: Indicatii/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(IndicatiiViewModel indicatiiVM)
        {
            if (ModelState.IsValid)
            {

                Indicatii indicatii = _indicatiiRepository.FindByCondition(m => m.IndicatiiID == indicatiiVM.IndicatiiID).FirstOrDefault();

                if (indicatii == null)
                {
                    return NotFound();
                }
                var boala = _boalaRepository.FindByCondition(boala => boala.Nume == indicatiiVM.Boala).FirstOrDefault();
                if (boala == null)
                {
                    boala = new Boala() { Nume = indicatiiVM.Boala };
                    _boalaRepository.Create(boala);
                    _boalaRepository.Save();
                }

                //setting other values
                indicatii.AlimentID = indicatiiVM.AlimentID;
                indicatii.BoalaID = boala.BoalaID;
                indicatii.Motiv = indicatiiVM.Motiv;

                //success
                _indicatiiRepository.Update(indicatii);
                _indicatiiRepository.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(indicatiiVM);
        }

        // GET: Indicatii/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var indicatie = _indicatiiRepository.FindByCondition(m => m.IndicatiiID == id).FirstOrDefault();
            if (indicatie == null)
            {
                return NotFound();
            }

            _indicatiiRepository.Delete(indicatie);
            _indicatiiRepository.Save();

            return RedirectToAction(nameof(Index));
        }
    }

}

GestionareRegimuri/Views/Indicatii/Create.cshtml
@model GestionareRegimuri.ViewModels.IndicatiiViewModel

@{ ViewData["Title"] = "Creare Indicatii"; }

<h1>Creare</h1>

<h4>Indicatie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Indicatii" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input asp-for="AlimentID" type="hidden" />
            <div class="form-group">
                <label asp-for="Boala" class="control-label"></label>
                <input asp-for="Boala" class="form-control" />
                <span asp-validation-for="Boala" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Motiv" class="control-label"></label>
                <input asp-for="Motiv" class="form-control" />
                <span asp-validation-for="Motiv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


<div>
    <a asp-action="Index">Index</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GestionareRegimuri/Views/Indicatii/Edit.cshtml
@model GestionareRegimuri.ViewModels.IndicatiiViewModel

@{ ViewData["Title"] = "Editare Indicatii"; }


<h1>Editare</h1>

<h4>Indicatie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IndicatiiID" />
            <div class="form-group">
                <label asp-for="AlimentID" class="control-label"></label>
                <input asp-for="AlimentID" class="form-control" />
                <span asp-validation-for="AlimentID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Boala" class="control-label"></label>
                <input asp-for="Boala" class="form-control" />
                <span asp-validation-for="Boala" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Motiv" class="control-label"></label>
                <input asp-for="Motiv" class="form-control" />
                <span asp-validation-for="Motiv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvare" class="btn btn-primary" />
                <button asp-action="Delete" class="btn btn-primary" asp-route-id="@Context.Request.Query["id"]">Sterge</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Anulare</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GestionareRegimuri/Views/Indicatii/Index.cshtml
@model IEnumerable<GestionareRegimuri.Models.Indicatii>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Creare noua indicatie</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Motiv)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Aliment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Boala)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Motiv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Aliment.Categorie)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Boala.Nume)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.IndicatiiID">Editare</a> |
                <a asp-action="Details" asp-route-id="@item.IndicatiiID">Detalii</a> |
                <a asp-action="Delete" asp-route-id="@item.IndicatiiID">Sterge</a>
            </td>
        </tr>
}
    </tbody>
</table>